config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  get   'team_daily_workload/chart'
  get   'static_pages/home'
  get   'static_pages/help'

  devise_for :users
  resources :team_daily_workload
  resources :workloads do
  	collection do
  		post :confirm
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team_daily_workload.rb
class TeamDailyWorkload < ApplicationRecord

	def index
		@workloads = Workload.unconfirmed # .group(:date)
		@team_scores = @workloads.sum(:score)
	end

	def uncofirmed_workloads_by_date
		Workload.unconfirmed
	end

	def unconfirmed_team_daily_workload_score
				uncofirmed_workloads_by_date.group(:date).sum(:score)/uncofirmed_workloads_by_date.count
	end

	def scores

	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workloads

  def full_name
  	[name, surname].join(" ")
  end
end

app/models/workload.rb
class Workload < ApplicationRecord
	belongs_to :user

	scope :unconfirmed, ->{ where(confirmed: [nil, false])}
	default_scope { order(created_at: :desc)}

	def self.uncnf_score_by_date(date)
		chosen_day = Workload.unconfirmed.where(date: date)
  	(chosen_day.sum(:score) / (chosen_day.count * 1/3))/3.0
	end

	def self.team_daily_workload(date)
		total_score = Workload.where(date: date).sum(:score)
		availability = Workload.where(date: date).count/3.0
		total_score / availability
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	attributes = [:name, :surname, :email]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/load_controller.rb
class LoadController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@load = Load.all
	end

	def new
		@load = Load.new
	end

	def create
		@load = Load.create(load_params)
		@load.user = current_user

		if @load.save
    	flash[:notice] = "Your load has been noted"
    	redirect_to root_path
    else
      flash.now[:alert] = "Nope. Something's wrong. Please try again."
      render :new
    end
	end

	private

		def load_params
			params.require(:load).permit(:score, :date)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/team_daily_workload_controller.rb
class TeamDailyWorkloadController < ApplicationController
  def chart
    @team_daily_workloads = TeamDailyWorkload.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/workloads_controller.rb
class WorkloadsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :confirm]
	before_action :set_workload, only: [:show, :edit]

	def confirm
		chosen_unconfirmed = Workload.unconfirmed.where('date = ?', params[:date])
		TeamDailyWorkload.create(day: params[:date], score: params[:score])
		chosen_unconfirmed.update_all(confirmed: true)

		redirect_to workloads_path
	end

	def index
		@unconfirmed = Workload.unconfirmed
		@workloads = Workload.all
	end

	def new
		@workload = Workload.new
	end

	def create
		@workload = Workload.create(workload_params)
		@workload.user = current_user

		if @workload.save
    	flash[:notice] = "Your load has been noted"
    	redirect_to root_path
    else
      flash.now[:alert] = "Nope. Something's wrong. Please try again."
      render :new
    end
	end

	def destroy
    unless @workload.user == current_user
      flash[:alert] = "You can only delete your own workload."
      redirect_to root_path
    else
      if @workload.destroy
        flash[:success] = "Workload has been deleted"
        redirect_to articles_path
      else
        flash.now[:alert] = "You need to sign in or sign up before continuing."
        render :show
      end
    end
	end

	private

		def workload_params
			params.require(:workload).permit(:score, :date, :checkpoint, :confirmed)
		end

		def set_workload
			@workload = Workload.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_daily_workload_helper.rb
module TeamDailyWorkloadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    	<% flash.each do |key, message| %>
    		<div class="text-center alert alert-<%= key =='notice'? 'success': 'danger' %>">
    			<%= message %>
    		</div>
    	<% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "PM Load App", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",      root_path %></li>
            <li><%= link_to "Score it!", new_workload_path %></li>
            <li><%= link_to "Workloads", workloads_path %></li>
            <li><%= link_to "Unconfirmed Workloads", team_daily_workload_index_path %></li>
            <li><%= link_to "Chart",     team_daily_workload_chart_path %>
            <li><%= link_to "Help",      static_pages_help_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
            <% if user_signed_in? %>
              <p class="navbar-text">
                Signed in as <%= "#{current_user.email}" %>
              </p>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
Na razie wersja robocza. Zobaczymy jak wyjdzie w praktyce i zmodyfikujemy.

Legenda:
1 - Nie potrafię sobie znaleźć zajęcia, poproszę o jakąś pracę.
2 - Nie mam zaległości typu pendingi, brakujące PO itp. W razie czego mogę komuś pomóc.
3 - Jest OK, jestem w miarę na bieżąco z pracą.
4 - Pracy jest sporo.
5 - Jest bardzo dużo pracy, mam czas tylko na bieżące zlecenia. Już mam zaległości.

6 - NIE używamy! A jak już użyjemy to oznacza, że tracimy zlecenia, zawalamy terminy, zagrożona jest współpraca z klientem itp. a my pracujemy mniej więcej w taki sposób:
http://www.reactiongifs.com/wp-content/uploads/2013/03/computing.gif
<a href="http://www.reactiongifs.com/wp-content/uploads/2013/03/computing.gif"></a>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the PM Workload App</h1>

  <h2>
	  This is the home page for the
	  <a href="http://stgambit.com/">PM Workload App</a>
	  sample application.
  </h2>

  <% if user_signed_in? %>
   		<%= link_to "Score now!", new_workload_path, class: "btn btn-lg btn-primary" %>
 	<% else %>
 			<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</div>

app/views/team_daily_workload/chart.html.erb
<h1>Wykres</h1>
<br>
<p><%= line_chart @team_daily_workloads.group(:day).sum(:score) %></p>

app/views/workloads/index.html.erb
<div class="panel-heading">
  <h1>Unconfirmed Team Workloads</h1>
</div>
<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Score</th>
    <th>Confirmed?</th>
    <th>Action</th>
  </tr>

  <% @unconfirmed.group(:date).each do |workload| %>
    <tr>
      <td><%= workload.date %></td>
      <td><%= score = @workloads.uncnf_score_by_date(workload.date).round(2) %></td>
      <td><%= workload.confirmed ? "yes" : "no" %></td>
      <td><%= link_to "Confirm", confirm_workloads_path(date: workload.date, score: score), method: :post,
                                 class: "btn btn-danger btn-xs" %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/workloads/new.html.erb
<h2>Score your current load</h2>

<%= form_for(@workload, url: {action: "create"}) do |f| %>
	<div class="form-group">
		<div class="control-label col-md-1">
			<%= f.label :score %>
		</div>
		<div class="col-md-1">
			<%= f.number_field :score, in: 1..6, step: 1, class: 'form-control', autofocus: true %>
		</div>
	</div>
	<div class="form-group">
		<div class="control-label col-md-1">
			<%= f.label :date %>
		</div>
		<div class="col-md-3">
			<%= f.date_select :date, class: 'form-control' %>
		</div>
	</div>
		<div class="form-group">
		<div class="control-label col-md-1">
			<%= f.label :checkpoint %>
		</div>
		<div class="col-md-1">
			<%= f.number_field :checkpoint, in: 10..16, step: 3.00, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-1 col-md-3">
			<%= f.submit class: "btn btn-primary btn-lg pull-right" %>
		</div>
	</div>
<% end %>